export const tiers = [
  {
    name: "free",
    id: "free",
    priceMonthly: "$0",
    unit: "free plan",
    plan: "free",
    amount: 0,
    currency: "usd",
    credits: 0,
    description: "",
    features: [
      "enjoy 4 AI-enhanced episodes",
      "no credit card required",
    ],
    featured: false,
  },
  {
    name: "standard",
    id: "standard",
    priceMonthly: "$5.9",
    unit: "per month",
    plan: "standard",
    amount: 590,
    currency: "usd",
    credits: 100,
    description: "",
    features: [
      "Unlimited access to AI-enhanced episodes",
      "Run AI on 20 episodes each month",
      "High-speed transcription",
      "High-quality transcription",
      "AI-assisted learning",
    ],
    featured: true,
    price_id: "prod_QeAF66o9ZPOXdg", // Stripe 为 Standard 计划生成的 price_id
  },
  {
    name: "pro",
    id: "pro",
    priceMonthly: "$11.9",
    unit: "per month",
    plan: "pro",
    amount: 1190,
    currency: "usd",
    credits: 200,
    description: "",
    features: [
      "Everything in Standard",
      "Run AI on 50 episodes each month",
      "Priority transcription",
      "High-quality transcription",
      "AI-assisted learning",
    ],
    featured: false,
    price_id: "prod_QeAFJJU5zI7I5Y", // Stripe 为 Pro 计划生成的 price_id
  },
];
